department-of-veterans-affairs/vets-api-clients

- appealsAPI/sample-data/1_form9.json
- appealsAPI/sample-data/2_hearing.json
- appealsAPI/sample-data/3_scheduled_hearing.json
- appealsAPI/sample-data/4_post_remand.json
adding appeals sample data for WH call center
> Leannammiller patch 1

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
So that this page will have a fuller range of options: https://github.com/department-of-veterans-affairs/vets-api-clients/issues/new/choose
> Add templates for bug reports and feature requests

- test_accounts.md
Reference ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/755 when adding new API users
> Adding API Test users to documentation

- oauth/node/README.md
- oauth/node/index.js
based on the code here: https://github.com/department-of-veterans-affairs/developer-portal/pull/52
> Update sample oauth code and add readme

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/general-feedback.md
- .github/ISSUE_TEMPLATE/support-request.md
This PR addresses [this issue](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1723) and creates a new `General Feedback` issue template.
> Add General Feedback issue template

- samples/oauth_rails/VetsApiClaims/README.md
- samples/oauth_rails/VetsApiClaims/app/assets/stylesheets/application.scss
- samples/oauth_rails/VetsApiClaims/app/controllers/claims_controller.rb
- samples/oauth_rails/VetsApiClaims/app/models/test_user.rb
- samples/oauth_rails/VetsApiClaims/app/services/schema_service.rb
- samples/oauth_rails/VetsApiClaims/app/views/claims/form_526.html.erb
- samples/oauth_rails/VetsApiClaims/app/views/claims/index.html.erb
- samples/oauth_rails/VetsApiClaims/app/views/claims/show.html.erb
- samples/oauth_rails/VetsApiClaims/app/views/layouts/application.html.erb
- samples/oauth_rails/VetsApiClaims/app/views/users/index.html.erb
- samples/oauth_rails/VetsApiClaims/config/routes.rb
- samples/oauth_rails/VetsApiClaims/package-lock.json
- samples/oauth_rails_vetverification/config/application.yml
This pull request is to bring in supporting documents for claims into the sample api app
> Claims supporting documents

- README.md
Removes email address in favor of link to support page.
> Update README.md with link to support page

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/general-feedback.md
- .github/ISSUE_TEMPLATE/support-request.md
- Path-to-Production.md
- README.md
- TermsofService.md
- services/vba_documents/README.md
- services/vba_documents/UnderstandingDocumentProcessing.md
- services/vba_documents/curl/README.md
- services/vba_documents/go/README.md
- services/vba_documents/go/cmd/docupload/README.md
- test_accounts.md
Added "Lighthouse" per outreach style guide for consistent branding.
> Add Lighthouse branding and developer portal links to repo wherever possible

- test_accounts.md
Needing to add all of the remaining test users resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/3524
- Add all remaining users to test against
> Adding remaining Test Users

- samples/oauth_php/VetsApiClaims/app/Http/Controllers/HomeController.php
this PR fixes the php sample app for the saml proxy changes for expires_at.
> fix php sample app expires time

- samples/oauth_pkce_cli/.gitignore
- samples/oauth_pkce_cli/README.md
- samples/oauth_pkce_cli/package.json
- samples/oauth_pkce_cli/pkce-cli
https://vasdvp.atlassian.net/browse/PIV-277
Add a sample client for use with PKCE.
> PIV-277 - Sample PKCE Client

- samples/benefits-intake/env.sample
- samples/oauth_node/index.js
- samples/oauth_php/VetsApiClaims/.env.example
- samples/oauth_php/VetsApiClaims/base64.php
- samples/oauth_rails/VetsApiClaims/app/controllers/documents_controller.rb
- samples/oauth_rails/VetsApiClaims/config/application.yml.EXAMPLE
- samples/oauth_rails/vethealth/app/controllers/session_controller.rb
- samples/oauth_rails/vethealth/app/models/health_api_response.rb
- samples/oauth_rails/vethealth/test/controllers/authentications_controller_test.rb
- samples/oauth_rails/vethealth/test/controllers/health_api_controller_test.rb
- samples/oauth_rails/vethealth/test/controllers/oauth_callbacks_controller_test.rb
- samples/oauth_rails/vethealth/test/controllers/session_controller_test.rb
- samples/oauth_rails/vethealth/test/models/authentication_test.rb
- samples/oauth_rails/vethealth/test/models/health_api_response_test.rb
- samples/oauth_rails/vetverification/app/controllers/auth_controller.rb
- samples/oauth_react/README.md
- test_accounts.md
Updating sample apps to point to sandbox.
> Repointing Sample Apps from dev to sandbox

- test_accounts.md
Updating VSO Representative Documentation for ticket https://vajira.max.gov/browse/API-670
> Updating Representative Information

- samples/oauth_rails/VetsApiClaims/app/views/pages/index.html.erb
Fixing typo on the homepage of rails sample app
> fixing typo on rails app

- samples/java/LighthouseBenefitsIntakeBase64/pom.xml
- samples/java/LighthouseBenefitsIntakeBase64/src/main/java/Main.java
This PR adds a java snippet for the benefits intake base64 uploads.
> add sample of base64 encoding to for benefits intake in java

- samples/oauth_rails/VetsApiClaims/app/controllers/claims_controller.rb
For ticket https://vajira.max.gov/browse/API-1276
> Moving all errored responses to alerts

- samples/oauth_pkce_cli/README.md
- samples/oauth_pkce_cli/pkce-cli
Alter the client using the PKCE flow to be able to use the isolated oauth endpoint configuration.
> API 1977 isolated oauth2 path PKCE client adjustment

- samples/oauth_pkce_cli/pkce-cli
Add a default auth server to the PKCE client.
> Default auth server to PKCE client

- samples/oauth_rails/VetsApiClaims/Gemfile
- samples/oauth_rails/VetsApiClaims/Gemfile.lock
- samples/oauth_rails/vethealth/Gemfile
One more update to the rails sample app to fix the action view dependency
> update rails version fo the oauth_rails vetsAPIClaims app

- samples/oauth_rails/VetsApiAppeals/app/views/layouts/application.html.erb
Add current environment to sample app's layout.
Ticket: https://vajira.max.gov/browse/API-5425
> Add environment text to layout

- samples/oauth_node/package-lock.json
- samples/oauth_node/package.json
Update sqllit3 dependency for sample node project
> Update sqlite3 dependency

- samples/oauth_node/index.js
Set default session values to remove undefined warnings.
> Set default session values

- samples/oauth_rails/VetsApiAppeals/app/controllers/nods_controller.rb
- samples/oauth_rails/VetsApiAppeals/app/services/nod_service.rb
- samples/oauth_rails/VetsApiAppeals/app/views/layouts/application.html.erb
- samples/oauth_rails/VetsApiAppeals/app/views/nods/new.html.erb
- samples/oauth_rails/VetsApiAppeals/app/views/nods/show.html.erb
- samples/oauth_rails/VetsApiAppeals/app/views/pages/index.html.erb
- samples/oauth_rails/VetsApiAppeals/config/routes.rb
- samples/oauth_rails/VetsApiAppeals/spec/fixtures/valid_10182_minimum.json
- samples/oauth_rails/VetsApiAppeals/spec/services/nod_service_spec.rb
- samples/oauth_rails/VetsApiAppeals/spec/support/vcr_cassettes/nod_get.yml
- samples/oauth_rails/VetsApiAppeals/spec/support/vcr_cassettes/nod_post.yml
- samples/oauth_rails/VetsApiAppeals/spec/support/vcr_cassettes/nod_schema.yml
[API-5040](https://vajira.max.gov/browse/API-5040)
This PR creates a sample environment for us to demonstrate and view created NODs. 
The behavior mimics that of HLR, and sets the state for upcoming oAuth changes.
> Api 5040/appeals nod show/create

- test_accounts/benefits_test_accounts.md
**Original Issue**
[API-9719](https://vajira.max.gov/browse/API-9719)
Updates "benefits_test_accounts.md" list to include user who also has Health Api data.
> [API-9719] - ClaimsApi - Add test account that also has health data

- samples/oauth_rails/VetsApiAppeals/app/services/hlr_service.rb
- samples/oauth_rails/VetsApiAppeals/app/views/hlrs/new.html.erb
> API-11164 - Update sample app to use hlr v2

- samples/oauth_rails/VetsApiAppeals/app/services/nod_service.rb
- samples/oauth_rails/VetsApiAppeals/app/views/nods/new.html.erb
Updates NOD header params to be current and fixes bug with NOD form not rendering.
https://vajira.max.gov/browse/API-11165
> API-11165 - Fix bug with NOD form displaying

- test_accounts/benefits_test_accounts.md
Updated the individual POA information, as well as some other cleanup/clarifications
https://vajira.max.gov/browse/API-10869
> Update POA information for claims reps

- test_accounts.md
Revised copy in a step-by-step way to make clear to the user that a) they use ID.me to sign in and b) they don’t have to enter any new information for the 2-FA.
> Update to test_accounts.md

- samples/oauth_rails/VetsApiAppeals/app/controllers/legacy_appeals_controller.rb
- samples/oauth_rails/VetsApiAppeals/app/services/legacy_appeal_service.rb
- samples/oauth_rails/VetsApiAppeals/app/views/layouts/application.html.erb
- samples/oauth_rails/VetsApiAppeals/app/views/legacy_appeals/index.html.erb
- samples/oauth_rails/VetsApiAppeals/app/views/pages/index.html.erb
- samples/oauth_rails/VetsApiAppeals/config/routes.rb
Initial work on legacy appeals...
https://vajira.max.gov/browse/API-11166
> API-11166 - Initial work on legacy appeals

- test_accounts/benefits_test_accounts.md
Updates the POA codes for test user representatives Tamara Ellis and John Doe.
> [API-12254] - ClaimsApi - Update individual poa codes for test reps

- samples/oauth_node/package-lock.json
- samples/oauth_node/package.json
API-000 OAuth Node dependency updates
Addresses a couple different `npm audit` items.  Validated with a local run.
> API-000 OAuth Node dependency updates

- samples/oauth_node/package-lock.json
- samples/oauth_node/package.json
oauth_node: Sqlite3 targeted dependency no longer exists; updating reference but uses same version.
Issue: https://vajira.max.gov/browse/API-14228
> oauth_node: Update Sqlite3 Reference

- test_accounts/health_test_accounts.md
Updated file link for health test patient data to be xlsx instead of csv
> API-14895 health test patient data link

- samples/oauth_node/package-lock.json
- samples/oauth_node/package.json
Updates oauth_node packages to resolve 6 security vulnerabilities.
issue: https://vajira.max.gov/browse/API-13667
> API-13667 Vulnerability Remediation

- samples/oauth_node/package-lock.json
Addresses https://vajira.max.gov/browse/API-18162
- audit fix removed the got dependency
> API-18162 npm audit fix

- samples/oauth_node/index.js
- samples/oauth_node/package-lock.json
- samples/oauth_node/package.json
Addresses https://vajira.max.gov/browse/API-18161
- updates passport dependency
This PR intended to follow https://github.com/department-of-veterans-affairs/vets-api-clients/pull/360
> API-18161 passport

- test_accounts/health_test_accounts.md
https://vajira.max.gov/browse/API-18830
~Update to master branch link for Health API Conditions Spreadsheet~
> The Health Test Patient Data on the line above includes all the Condition information and is supposed to be updated on change while this spreadsheet is static and has not been updated in over a year.
Per feedback removal of the Conditions Spreadsheet link in favor of the Health Test Patient Data spreadsheet.
> Update link for Health API Conditions Spreadsheet

- samples/oauth_node/package-lock.json
Resolves minimatch ReDoS vulnerability
> API-21334 upgrade minimatch

- test_accounts/clinical_health_test_accounts.md
[API-26522](https://vajira.max.gov/browse/API-26522)
> API 26522 add new github page for clinical health test patients

- samples/oauth_node/index.js
> Update default to V2 VV

- samples/oauth_node/package-lock.json
- samples/oauth_node/package.json
oauth_node
- npm update and npm audit fix 
- tested against sandbox with user 003
> API-000 update node packages

- samples/oauth_node/package-lock.json
> API-000 audit fix

- test_accounts/benefits_test_accounts.md
:x: https://developer.va.gov/explore/api/benefits/test-users
:white_check_mark: https://developer.va.gov/explore/api/benefits-claims/test-users
> API-000 Correct test data link - benefits_test_accounts.md
