department-of-veterans-affairs/vets-api-clients

test_accounts.md

I realized I never added the Non-Veteran test user to the documentation.

Adding Non-Veteran Test user to Documentation

---

README.md

This adds a paragraph to the bottom of `vets-api-clients` README.md with a link to Lighthouse Statuspage.

Update README.md to include Statuspage link

---

test_accounts.md

Adding new test users that were created for USA Jobs to the table of OAuth test users. 
Note: va.api.user+idme.008@gmail.com is ID.me, but not on of the users I created and only has MVI profile data in mockdata repo.
For department-of-veterans-affairs/vets-contrib/issues/3460.

Add new test users to table

---

samples/oauth_rails/VetsApiClaims/app/models/session.rb

The oauth response is now sending an expires_in key vs expires_at. This PR fixes the sample app to use the new key for the session expire time.

fix oauth login for expires_at key removal

---

samples/oauth_node/index.js

This is addressing issue around the oauth node sample app not handling the Auth server sending back an error when authenticating as a veteran.
https://vasdvp.atlassian.net/browse/PIV-242
I would like to note that when I was first testing this I saw that the error being passed back is from not registering my test Okta account with the callback url required by this sample app: http://localhost:8080/auth/cb. This will display the error more nicely at least but we should probably consider how to either provide test app credentials or warn people that they need this as a registered URI.

Displaying error_description

---

samples/oauth_node/index.js

Addresses behavior we were seeing where we were seeing the sample OAuth Node app timing out after logging in to Id.me with a sample veteran.
https://vasdvp.atlassian.net/browse/PIV-274

Stop timing out

---

test_accounts.md

2nd pass at this.  I'm hoping someone has a shortcut to removing the Password column for Health API users and moving the Usernames to the leftmost column for both sets.

Improve Test Accounts document

---

test_accounts.md

We discovered that 001 and 007 do indeed have PoA for 002, so revised that copy and added the 401 error that should be returned when you try to access 008's data when logged in as 007.  Also corrected `ID.met` to `ID.me` throughout.

Correct PoA for 002, add 008

---

samples/oauth_rails/VetsApiClaims/app/controllers/claims_controller.rb
samples/oauth_rails/VetsApiClaims/app/services/schema_service.rb
samples/oauth_rails/VetsApiClaims/app/views/claims/form.html.erb

Not sure how we didn't catch this in our feature branch testing but the redirect should be redirecting to /active in the sample app since there is no show end point to look this up on.
{"errors":[\{"title":"Not found","detail":"There are no routes matching your request: services/claims/v1/forms/0966/184461","code":"411","status":"404"}
]}
For Ticket https://vajira.max.gov/browse/API-2162

Fixing 0966 Submission redirection

---

samples/oauth_react/README.md

This PR updates the readme for the Oauth React app. The scope needs to be able to be passed in as a single string vs an array of strings.
For reference 
https://vajira.max.gov/browse/API-2132
and
fixes https://github.com/department-of-veterans-affairs/vets-api-clients/issues/182

Api 2132 react oauth empty page

---

samples/oauth_php/VetsApiClaims/app/Exceptions/Handler.php
samples/oauth_php/VetsApiClaims/composer.json
samples/oauth_php/VetsApiClaims/composer.lock
samples/oauth_php/VetsApiClaims/phpunit.xml

Rather than another small bump via #215 this will update all the PHP packages to their current latest versions (or close to them) so that future dependabot updates are against current versions that people are more likely to be using.

Update Laravel and other packages to latest

---

samples/oauth_react/README.md

The README for the React sample app lists a deprecated URL on deptva-eval.okta.com for its `authority`.  Correcting to sandbox-api.va.gov.

Correct authority URL for sample React app (Veteran Verification)

---

test_accounts/benefits_test_accounts.md

Updates documentation a bit to recognize that POA for Veteran's is not set in stone in sandbox. POA can change/be changed in sandbox using the POA update endpoint within the Claims API.

API-5824: Issue keeping POA for Veteran's in sandbox the same as what is documented

---

test_accounts/benefits_test_accounts.md

Added a bit of documentation around which poa codes are associated with our mock representatives in sandbox.
https://vajira.max.gov/browse/API-6518

API-6518: Document POA codes in sandbox

---

test_accounts/verification_test_accounts.md

Per customers request created a test user with the following values.
- Character of Service (discharge_status) of 'Uncharacterized'
- Disability rating of 30% or more
- Disability letter of 01/01/1991
Note:
The new disabilities data is not yet up in sandbox. We will need to manually deploy mock-bgs for the data to be up to date.

Added 012 to VV Test Users

---

test_accounts/benefits_test_accounts.md
test_accounts/health_test_accounts.md
test_accounts/verification_test_accounts.md

Rewrite the content for verification_test_accounts.md, benefits_test_accounts.md, and health_test_accounts.md to have a step-by-step way of logging in to the sandbox environment. This makes clear to the user that a) they use ID.me to sign in and b) they don’t have to enter any new information for the 2-FA.

API-6349 content changes for VV, Benefits, and Health APIs

---

samples/oauth_node/Dockerfile
samples/oauth_node/package-lock.json
samples/oauth_node/package.json

API-000 Update OAuth Node Dockerfile base to Node 16
- Upgrade Dockerfile Base image `FROM node:16`
- Updates `openid-client` to latest version
- Updates `sqlite3` to latest version
Addresses error with openid-client incompatibility with old Node 10 version.
```
$ cd vets-api-clients/samples/oauth_node/
$ docker run -p 8080:8080 oauth-node-sample-client
/app/node_modules/openid-client/lib/issuer.js:32
#metadata;
^
SyntaxError: Invalid or unexpected token
at Module._compile (internal/modules/cjs/loader.js:723:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require …
```

API-000 Update OAuth Node Dockerfile base to Node 16

---

test_accounts/health_test_accounts.md

With the addition of the Health Patient Test Data spreadsheet, the COVID sections have been rendered redundant.

Remove COVID specific text and sections

---

samples/oauth_node/README.md
samples/oauth_pkce_cli/README.md

Update README.md for oauth_node & PKCE sample apps to call out Node 16 as current supported/tested version.
Future update may include additional supported versions after testing.

OAuth Samples Readme - Specify Node 16 working version

---

test_accounts/health_test_accounts.md

The excel file referenced here became unavailable when the synthetic records repo was made internal as part of the LHDI migration process. The new [Lighthouse FHIR APIs Consumer Docs](https://github.com/department-of-veterans-affairs/lighthouse-fhir-apis-consumer-docs/tree/main) repo is intended to stay public and house any documentation we plan to make accessible to consumers through our public docs.

API-37596-point-to-public-file

---

test_accounts/appealable_issues_test_accounts.md
test_accounts/appeals_status_test_accounts.md
test_accounts/legacy_appeals_test_accounts.md

This PR updates the Appealable Issues API, Appeals Status v1 API, and Legacy Appeals API test account pages to account for changes made to the APIs since these pages were created, including:
1. The removal of the `X-VA-User` header from the Appeals Status v1 API.
2. A change to the `icn` URL parameter in all three APIs, where it's not required if the request is using a veteran-scoped token.
3. A change to the mocked response returned for the Greg Anderson test user, a 502 error rather than a 500 error.
Looking for feedback on whether or not the modified instructions are clear for API consumers. Suggestions for improvement are welcome.

API-41583: Update Appeals API Test Account Pages for API Changes

---

test_accounts/appealable_issues_test_accounts.md
test_accounts/appeals_status_test_accounts.md
test_accounts/legacy_appeals_test_accounts.md

This PR updates the Appealable Issues API, Appeals Status v1 API, and Legacy Appeals API test account pages to remove the 502 error test account. It is being removed due to an error occurring in the Sandbox environment.

API-42883: Remove 502 Error Example for Appeals APIs
